DROP DATABASE IF EXISTS DIE;
CREATE DATABASE DIE;
USE DIE;

CREATE TABLE Dir(
    dID INT PRIMARY KEY AUTO_INCREMENT,
    dName VARCHAR(200) NOT NULL,
    dPassword VARCHAR(45),
    dFatherId INT NOT NULL
);

CREATE TABLE Fl(
    fID INT PRIMARY KEY AUTO_INCREMENT,
    fName VARCHAR(200) NOT NULL,
    fDirID INT NOT NULL,
    foreign key(fDirID) references Dir(dID) on delete CASCADE 
);